Fix 'dev-rust/cargo-999-r1.ebuild'

diff --git a/dev-rust/cargo/files/cargo-no-sanity-check.patch b/dev-rust/cargo/files/cargo-no-sanity-check.patch
--- a/dev-rust/cargo/files/cargo-no-sanity-check.patch
+++ b/dev-rust/cargo/files/cargo-no-sanity-check.patch
@@ -1,45 +1,12 @@
+diff -uN a/install.sh b/install.sh
 --- a/install.sh	2014-12-21 16:54:41.000000000 +0900
-+++ b/install.sh	2014-12-22 02:56:28.426667115 +0900
-@@ -370,28 +370,6 @@
-     fi
- fi
-
--# Sanity check: can we can write to the destination?
--msg "verifying destination is writable"
--umask 022 && mkdir -p "${CFG_LIBDIR}"
--need_ok "can't write to destination. consider \`sudo\`."
--touch "${CFG_LIBDIR}/rust-install-probe" > /dev/null
--if [ $? -ne 0 ]
--then
--    err "can't write to destination. consider \`sudo\`."
--fi
--rm -f "${CFG_LIBDIR}/rust-install-probe"
--need_ok "failed to remove install probe"
--
--# Sanity check: don't install to the directory containing the installer.
--# That would surely cause chaos.
--msg "verifying destination is not the same as source"
--INSTALLER_DIR="$(cd $(dirname $0) && pwd)"
--PREFIX_DIR="$(cd ${CFG_PREFIX} && pwd)"
--if [ "${INSTALLER_DIR}" = "${PREFIX_DIR}" ]
--then
--    err "can't install to same directory as installer"
--fi
--
- # Using an absolute path to libdir in a few places so that the status
- # messages are consistently using absolute paths.
- absolutify "${CFG_LIBDIR}"
-@@ -454,14 +432,6 @@
-     exit 0
- fi
-
--# Create the installed manifest, which we will fill in with absolute file paths
--mkdir -p "${CFG_LIBDIR}/${TEMPLATE_REL_MANIFEST_DIR}"
--need_ok "failed to create ${TEMPLATE_REL_MANIFEST_DIR}"
--touch "${INSTALLED_MANIFEST}"
--need_ok "failed to create installed manifest"
--
--msg
--
- # Now install, iterate through the new manifest and copy files
- while read p; do
++++ b/install.sh	2014-12-23 23:37:52.519206694 +0900
+@@ -511,7 +489,7 @@
+ # Run ldconfig to make dynamic libraries available to the linker
+ if [ "$CFG_OSTYPE" = "unknown-linux-gnu" ]
+     then
+-    ldconfig
++    : # ldconfig
+     if [ $? -ne 0 ]
+     then
+         warn "failed to run ldconfig."
